### ISSUE TITLE
关于绕过必应过滤器和禁用搜索

### ISSUE THREAD

**Issue by NijikaMyWaifu** [JayGarland/Autoreply_Sydneybot_Reddit#1]
https://github.com/JayGarland/Autoreply_Sydneybot_Reddit/blob/d0aec306b32454bf41157ce220d915b005504511/sydney.py#L27

`nojbfedge` 改成 `nojbf` 即可（使用 `nojbf` 后将会切换到 3 月 17 日前的老过滤器，仍有少部分内容可能触发）

https://github.com/JayGarland/Autoreply_Sydneybot_Reddit/blob/d0aec306b32454bf41157ce220d915b005504511/sydney.py#L256

`no_search` 设置为 True 可启用必应官方的 nosearch 模式

**Comment by NijikaMyWaifu** [comment]
另外让 Bing 不要调用画图可以试试用旧的基于 GPT-4 的平衡模式
https://github.com/JayGarland/Autoreply_Sydneybot_Reddit/blob/d0aec306b32454bf41157ce220d915b005504511/sydney.py#L33

`galileo` 改成 `harmonyv3` 然后主程序 `ask_stream` 函数调用里设置 `balanced` 风格

如果要画图可以要求 Bing 必须生成英文绘画 prompt，然后调用其他绘画服务

**Comment by NijikaMyWaifu** [comment]
还有你不小心暴露了你的 Cookies，建议用 orphan 分支来删除提交历史，或者直接删除仓库重建

**Comment by JayGarland** [comment]
> 还有你不小心暴露了你的 Cookies，建议用 orphan 分支来删除提交历史，或者直接删除仓库重建

谢谢提醒!

**Comment by JayGarland** [comment]
你的帮助和建议很有用!

**Comment by JayGarland** [comment]
> 还有你不小心暴露了你的 Cookies，建议用 orphan 分支来删除提交历史，或者直接删除仓库重建

Can you remove or jailbreak Blurring Face setting when I use an image to chat with sydney?
